name: mikoxl
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  hive_ce: ^2.11.4
  hive_ce_flutter: ^2.3.2
  hive_ce_generator: ^1.9.0
  path_provider: ^2.1.5
  freezed_annotation: ^3.1.0
  injectable: ^2.5.1
  iconsax: ^0.0.8
  tmdb_api_kit: 
      git: https://github.com/bilbilaki/tmdb_apik/
  cached_network_image: ^3.4.1
  worker_pool: ^0.0.5
  responsive_framework: ^1.5.1
  json_annotation: ^4.9.0
  auto_route: ^9.2.2
  flutter_riverpod: ^2.5.1
  dio: ^5.6.0
  shimmer: ^3.0.0
  logger: ^2.6.1
  flutter_hooks: ^0.21.3+1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.9.0
  auto_route_generator: ^9.2.2

  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true

  assets:
     - assets/